services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  hive-metastore:
    image: bitsondatadev/hive-metastore:latest
    container_name: hive-metastore
    ports:
      - "9083:9083"
    environment:
      DB_DRIVER: mysql
      DB_URL: jdbc:mysql://mysql:3306/metastore_db?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASS: root
    depends_on:
      - mysql

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioaccess
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  olake:
    image: source-mysql
    volumes:
      - ./olake-config:/mnt/config
    command: ["discover", "--config", "/mnt/config/config.json"]
    depends_on:
      - mysql
      - hive-metastore
      - minio

volumes:
  mysql_data:
  minio_data:
 